name: Commit CI

on:
  push:
    branches:
      - 'master'
    tags:
      - '![0-9]+.*'
  pull_request:

jobs:
  linux:
    uses: ./.github/workflows/linux-build.yml

  macos:
    uses: ./.github/workflows/macos-build.yml
    with:
      build_variant: '-universal'
      rime_plugins: rime/librime-charcode hchunhui/librime-lua lotem/librime-octagram

  windows:
    uses: ./.github/workflows/windows-build.yml
    with:
      rime_plugins: rime/librime-charcode hchunhui/librime-lua lotem/librime-octagram
